# Generated by Django 3.2.12 on 2024-03-08 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('pol', 'politics'), ('art', 'art'), ('tech', 'technology'), ('trivia', 'trivial news')], default='unknown', max_length=32)),
                ('region', models.CharField(choices=[('eu', 'europe'), ('uk', 'United Kingdom'), ('w', 'World News')], max_length=32)),
                ('date', models.DateField()),
                ('details', models.CharField(max_length=128)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.author')),
            ],
        ),
    ]
