# Generated by Django 3.2.12 on 2024-03-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_author_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.CharField(choices=[('pol', 'Politics'), ('art', 'Art'), ('tech', 'Technology'), ('trivia', 'Trivial News')], default='unknown', max_length=32),
        ),
        migrations.AlterField(
            model_name='story',
            name='region',
            field=models.CharField(choices=[('eu', 'Europe'), ('uk', 'United Kingdom'), ('w', 'World News')], max_length=32),
        ),
    ]
